### ISSUE TITLE
Failed to render and update auto layout status.

### ISSUE THREAD

**Issue by karthikmandava7** [gordoneliel/LinearProgressBar#20]
@gordoneliel when installing using pod it's saying failed to render and update auto layouts.
![screen shot 2018-05-04 at 10 34 33 am](https://user-images.githubusercontent.com/23091328/39613708-d63ba998-4f86-11e8-8d77-dc50d5b2b467.png)

**Comment by Jayze24** [comment]
[https://github.com/dji-sdk/Mobile-UXSDK-iOS/issues/24#issuecomment-383380822](url)

Its is the problem with Cocoapod version 1.5.0
If you are using this you will get this error.

To remove your current version you could just run:

sudo gem uninstall cocoapods

you can install a specific version of cocoa pods via the following command:

sudo gem install cocoapods -v 1.4.0

**Comment by gordoneliel** [comment]
Updated cocoapod, let me know if its still an issue
